package OO.House;

/*  Siga pelo código da classe Peter para entender a implementação...
* */

public class Peter {    //Peter foi deixado público para ser acessado pelo "TestFamily"...
    private String secrets = "secrets of Peter";    //Os segredos de Peter só ele conhece...
    String hobby = "baseball"; //O hobby de Peter pode ser conhecido só por quem está na mesma casa...
    protected String mannerOfSpeaking = "low speaking"; //O jeito de falar de Peter pode ser visto por quem está na casa e quem herda dele...
    public String job = "lawer"; //O emprego de Peter pode ser conhecido por qualquer pessoa...
    final Ana WIFE; //Peter pode ter uma esposa...

    public Peter(Ana wife){ //Note que Peter tem que receber um objeto Ana para ter uma esposa
        this.WIFE = wife;   //fizemos isso para gerar um relacionamento 1 + 1 por composição
    }                       //sem gerar um stackoverflow entre as classes...

    public void whatOnlyPeterKnows(){ //Classe pública para ser acessada pela classe "TestFamily"...
        System.out.println("Only Peter knows: " + secrets);
    }

    public void whatPeterKnowsAboutAllInYourHouse(){ //Classe pública para ser acessada pela classe "TestFamily"...
        System.out.println("Wife job: " + WIFE.job);
        System.out.println("Wife hobby: " + WIFE.hobby);
        System.out.println("Wife manner of speaking: " + WIFE.mannerOfSpeaking);
    }
    public void whatAllKnowAboutPeter(){ //Classe pública para ser acessada pela classe "TestFamily"...
        System.out.println("All know Peter's job: " + job);
    }

    // SIGA AGORA PARA A CLASSE Paul...
}
