package OO.Job;

/*  Note que o amigo de Paul não precisa de herança ou composição,
*   ele já é composto por Paul.
*   Siga o código para ver a implementação dos modificadores de
*   acesso...
* */

public class FriendsPaul { //Carl foi deixado público para ser acessado por "TestFamily"...
    private String secrets = "secrets of Friend's Paul"; //Os segredos de Carl só ele sabe...
    String hobby = "video game"; //O hobby de Carl só pode ser conhecido pelo pessoal do trabalho...
    protected String mannerOfSpeaking = "very fast"; //O jeito de falar de Carl pode ser visto por quem trabalha com ele e quem herdar dele...
    public String job = "developer"; //A profissão de Carl pode ser conhecida por qualquer um...

    //SIGA PARA A CLASSE TestFamily para ver como instanciamos e chamamos as instancias das classes...
}
